Repository Graylog2/graylog-plugin-collector, pull requests merged in 2019-01, with the labels that each got.

#97 Rename the system configuration for old Collectors
  src/web/system-configuration/CollectorSystemConfiguration.jsx
Labels: backport, enhancement, ready-for-review, ux

#98 Rename the system configuration for old Collectors (#97)
  src/web/system-configuration/CollectorSystemConfiguration.jsx
Labels: backport, ready-for-review

#99 Using pinned versions for shared dependencies from graylog-web-plugin.
  yarn.lock
Labels: ready-for-review

#100 Using pinned versions for shared dependencies from graylog-web-plugin.
  yarn.lock
Labels: ready-for-review
